# Generated by Django 3.0.2 on 2023-04-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230403_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='myuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_No', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('Balance', models.IntegerField()),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
